### PR TITLE
Split polyform-validators into mutliple libs

### PR DESCRIPTION
**Pull request by paluh**
I made a proper release of the old lib with deprecation warning.

### CODE REVIEW

**Comment by f-f** [comment]
@paluh I get a 404 for [the new url of `polyform-validators`](https://github.com/lambdaterms/polyform-validators)

**Comment by paluh** [comment]
@f-f I'm really sorry about that.  I fixed this URL just now. Did I somehow missed the result of CI? Could you please tell me if I should perform some verification step before opening a PR?
Once again - sorry for wasting your time on my stupid mistake!

**Comment by f-f** [comment]
@paluh no worries, you didn't miss anything - we don't have any CI check right now to verify that a package does not 404, but we should definitely add one. I did check manually because we're doing an unconventional operation

**Review by f-f — APPROVED** [review]
Anyways, this looks good now, thanks for fixing it up :slightly_smiling_face:

**Pull request merged**
