### PR TITLE
purifix: run registry-app with `nix run`

### PR DESCRIPTION
**Pull request by considerate**

### CODE REVIEW

**Comment by f-f** [comment]
Is the deletion of the `package-lock` accidental?

**Comment by considerate** [comment]
I didn't delete the `package-lock.json` file. I updated from `lockfileVersion: 2`  to `lockfileVersion: 3` which deletes half of the lockfile (the "dependencies" part).

**Comment by f-f** [comment]
Ah, sorry! The github UI made it look like it was deleted 😅

**Review by f-f — APPROVED** [review]

**Comment by considerate** [comment]
@f-f No worries, the large diff did make it look like the file was gone altogether in the GitHub UI.

Thanks for the quick review!

**Pull request merged**
