### PR TITLE
Upgrade spago to latest

### PR DESCRIPTION
**Pull request by f-f**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
That’s an interesting error — I wonder what changed? If you’re using the version parser you’ll want to switch to lenient parsing for things that start with a ‘v’ prefix.

**Comment by MonoidMusician** [comment]
Hm LegacyVersion is in app, though, and spago isn't depending on app yet (just lib and foreign).

**Comment by MonoidMusician** [comment]
PR: https://github.com/purescript/spago/pull/932

**Comment by f-f** [comment]
Yeah, this broke because we were using lenient version parsing everywhere. Spaghetto has no tests at the moment, so a few things might still break (we didn't get to exercise this code path on our work repo, as we bypass all the Node stuff)

**Comment by f-f** [comment]
This should do a little better now?

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
