### PR TITLE
Adds purescript-event and purescript-behaviors

### PR DESCRIPTION
**Pull request by mikesol**
Making FRP uncool again...

### CODE REVIEW

**Comment by f-f** [comment]
It looks like there are already some libraries registered with these names, could you pick new ones?

**Comment by srghma** [comment]
> could you pick new ones

that's the reason why I have created this org https://github.com/purescript-open-community/

we can move these packages there

**Comment by mikesol** [comment]
> It looks like there are already some libraries registered with these names, could you pick new ones?

Definitely doable, although I can also ask the original author if he'll transfer the archived repos to my account. If that's the case, would it be possible to keep the original name? This is to avoid having two libraries that do the same thing - one that works pre-0.14 (the original) and one 0.14 onwards (the fork).

**Comment by f-f** [comment]
> Definitely doable, although I can also ask the original author if he'll transfer the archived repos to my account. If that's the case, would it be possible to keep the original name?

Yes, in that case it would be possible to keep the original names!

**Comment by thomashoneyman** [comment]
@mikesol We've already discussed the situation with the original author and they'd like to keep the archived repos under their account (though they're fine with them being forked under new names).

**Comment by mikesol** [comment]
Got it, makes sense!

I'm wondering what the best move is from a community perspective? Is there a naming convention you feel would adequately communicate that the new package is forked from the old one and is not, at least in the short term, intended to be any different other than versioning updates (ie purescript-event-fork1 or purescript-event-post0.14)?

Mike Solomon
C.E.O. @Meeshkan
https://www.meeshkan.com

Sent via Superhuman ( ***@***.*** )

**Comment by mikesol** [comment]
Btw Serhii I think the project looks cool! In this case I'm not sure it's a good fit as it seems like these packages will gel with the registry after we sort out the details, but I will definitely keep it in mind for future projects.

Mike Solomon
C.E.O. @Meeshkan
https://www.meeshkan.com

Sent via Superhuman ( ***@***.*** )

**Comment by thomashoneyman** [comment]
I think the approach taken by @srghma in creating https://github.com/purescript-open-community makes it clear packages are being maintained despite being archived by their original authors.

**Pull request closed without merging**
