### PR TITLE
Add array-search, assert-multiple, huffman, maps-eager, repr and roman

### PR DESCRIPTION
**Pull request by JoelLefkowitz**

### CODE REVIEW

**Comment by f-f** [comment]
@JoelLefkowitz it looks like you didn't use `pulp` to publish these - so they are missing a `bower.json`. Could you add one?

**Comment by JoelLefkowitz** [comment]
I've been using spago as a package manager. I can copy the dependencies over to a bower.json but when I try using bower to install the dependencies and then pulp as a build tool  my build errors:

`Module Prim.Coerce was not found`

I think this is because the version of psc that pulp uses is old.

**Comment by f-f** [comment]
Yeah it looks like you might have several `purs` executables in your path?

**Comment by f-f** [comment]
@JoelLefkowitz any update on this?

**Comment by JoelLefkowitz** [comment]
Fixing now, sorry for the delay

**Comment by JoelLefkowitz** [comment]
Should be good to go now

**Comment by f-f** [comment]
Great, thank you!

**Review by f-f — APPROVED** [review]

**Pull request merged**
