### PR TITLE
Update spago.yaml: set -> package_set

### PR DESCRIPTION
**Pull request by MonoidMusician**
https://github.com/purescript/spago/pull/936

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Can this be done alongside an upgrade to the latest Spago? If they go in separately then the build is broken.

**Comment by MonoidMusician** [comment]
Yeah, I didn’t mean to merge this immediately, just leave it open as a reminder for when we do upgrade the spago dep

**Comment by thomashoneyman** [comment]
cc: @f-f

**Comment by f-f** [comment]
Merged and released, if you run `nix flake update` it should all be sorted out

**Review by thomashoneyman — APPROVED** [review]

**Comment by MonoidMusician** [comment]
Thanks! :)

**Pull request merged**
